harshitblog/accounts/urls.py
from django.conf.urls import url
from .import views
app_name="accounts"


urlpatterns=[
    url('signup',views.signups,name="signup"),  
    url('login',views.logins,name='login'),
    url('logout',views.logouts,name='logout')
]

harshitblog/blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static 
from django.conf import settings
from . import views

app_name="Harshit"

urlpatterns = [
    path("",views.home,name="home"),
    path("blog/<str:a>",views.data,name="blogs"),
    path('create',views.create_article,name="create")

]


urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

harshitblog/harshitblog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path("accounts",include('accounts.urls'))
    
]

harshitblog/accounts/models.py
from django.db import models

# Create your models here.

harshitblog/blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Blog(models.Model):
    name=models.CharField(max_length=200,default="",blank=True)
    title = models.CharField(max_length=200)
    body=models.TextField()     
    date=models.DateTimeField(auto_now_add=True)
    pic=models.ImageField(default='default.png',blank=True)
    author=models.ForeignKey(User,default=None,on_delete=models.CASCADE)

    def snippet(self):
        return self.body[0:50]+"......"


#python manage.py makemigrations
#python manage.py migrate

def __str__(self):
    return self.title

harshitblog/blog/forms.py
from django import forms
from . import models

class CreateBlog(forms.ModelForm):
    class Meta:
        model=models.Blog
        fields=['title','body','pic']

harshitblog/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout 
# Create your views here.

def signups(request):

    if request.method=='POST':
        form=UserCreationForm(request.POST)

        if form.is_valid():
            user=form.save()
            login(request,user)
            return redirect('Harshit:home')

    form = UserCreationForm()
    return render(request,'accounts/signup.html',{'form':form})


def logins(request):


    if request.method=='POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            user=form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:    
                return redirect('Harshit:home')

    else:
        form=AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})    


def logouts(request):
    if request.method=='POST':
        logout(request)
        return redirect('Harshit:home')

harshitblog/blog/views.py
from django.shortcuts import render,redirect
from .models import Blog
from django.http import HttpResponse,JsonResponse
from django.contrib.auth.decorators import login_required
from . import forms
# Create your views here.
def home(request):
    blogs=Blog.objects.all().order_by('date')
    return render (request,'index.html',{'blogs':blogs})


def data(request,a):
    a=Blog.objects.get(title=a)
    return render(request,'blog_detail.html',{'b':a})


@login_required(login_url="/accounts/login/")
def create_article(request):
    if request.method=='POST':
        form=forms.CreateBlog(request.POST,request.FILES)
        if form.is_valid():
            instance=form.save(commit=False)
            instance.author=request.user
            instance.save()
            return redirect('Harshit:home')
    else:
        form=forms.CreateBlog()
        return render(request,'article_create.html',{'form':form})

harshitblog/accounts/templates/accounts/login.html
{% extends 'index.html'%} {%load static%} {%block content%}
<link rel="stylesheet" href="{% static 'style.css' %}">
<p>Log in</p>
<form style='color:white' class='site-form' method='post' action="{%url 'accounts:login'%}">
    {%csrf_token%} {{form}} {%if request.GET.next %}
    <input type="hidden" name="next" value="{{request.GET.next}}"> {% endif %}
    <input type="submit" value="Login">
</form>
{%endblock%}

harshitblog/accounts/templates/accounts/signup.html
{% extends 'index.html'%} {%load static%} {%block content%}
<link rel="stylesheet" href="{% static 'style.css' %}">
<p>Signup</p>
<form style='color:white' class='site-form' method='post' action='/accounts/signup'>
    {%csrf_token%} {{form}}
    <input type="submit" value="signup">
</form>
{%endblock%}

harshitblog/blog/templates/article_create.html
{%extends 'index.html'%} {%block content%}

<div class="create-article">
    <h3> Create an Article </h3>
    <form class="site-form" action="{% url 'Harshit:create'%}" method="post" enctype="multipart/form-data">
        {%csrf_token%} {{form}}
        <input type="submit" value="create">
    </form>
</div>

{%endblock%}

harshitblog/blog/templates/blog_detail.html
{% extends 'index.html' %} {% block content%}
<h1>
    {{b.title}}
</h1>
<p>
    {{b.body}}
</p>
<p>
    {{b.date}}
</p>
<p>
    Written By :{{b.author}}
</p>
<img src="{{b.pic.url}}" /> {%endblock%}

harshitblog/blog/templates/index.html
<!DOCTYPE html> {%load static%}
<html lang="en">
<link rel="stylesheet" href="{% static 'style.css' %}">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django</title>
</head>

<body>
    <p><a href="{% url 'Harshit:home'%}">BLOGLOGO</a></p>
    <nav>
        <ul>
            {%if user.is_authenticated %}
            <li>
                <form class="logout-link " action="{% url 'accounts:logout'%}" method="post">
                    {%csrf_token%}
                    <button type="sumbit">Logout</button>
                </form>
            </li>
            <li>
                <a href="{% url 'Harshit:create'}">Write a Blog</a>
            </li>
            {%else%}
            <li>
                <a href="{% url 'accounts:login'%}">Login</a>
                <a href="{% url 'accounts:signup'%}">Signup</a>
            </li>
            {%endif%}
        </ul>
    </nav>
    {% for blog in blogs %}
    <div>
        <h1><a href="{% url 'Harshit:blogs' a=blog.title%}">{{blog.title}}</a></h1>
        <p>{{ blog.snippet}}</p>
        <p>{{blog.date}}</p>
        <p>Written By :{{b.author}}</p>
    </div>
    {%endfor%}
    <div class="blas">
        {% block content%} {%endblock%}
    </div>

</body>

</html>